
////
This file is generated! See _meta/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Httppollerbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-cloud>>
* <<exported-fields-httppollerbeat>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-cloud]]
== Cloud Provider Metadata Fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== meta.cloud.provider

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== meta.cloud.instance_id

Instance ID of the host machine.


[float]
=== meta.cloud.machine_type

example: t2.medium

Machine type of the host machine.


[float]
=== meta.cloud.availability_zone

example: us-east-1c

Availability zone in which this host is running.


[float]
=== meta.cloud.project_id

example: project-x

Name of the project in Google Cloud.


[float]
=== meta.cloud.region

Region in which this host is running.


[[exported-fields-httppollerbeat]]
== httppollerbeat Fields

None


[float]
=== url

type: text

required: True

The url pull


[float]
=== github_repository_fullname

type: keyword

required: False

The full name of the repository


[float]
=== github_repository_owner

type: keyword

required: False

The owner of the repository


[float]
=== github_repository_name

type: keyword

required: False

The name of the repository


[float]
=== github_repository_forks_count

type: long

required: False

The count of forks for the repository


[float]
=== github_repository_pull_requests_count

type: long

required: False

The count of pull request for the repository


[float]
=== github_repository_open_issues_count

type: long

required: False

The count of open issues for the repository


[float]
=== github_repository_stargazers_count

type: long

required: False

The count of stargazers for the repository


[float]
=== dockerhub_repository_fullname

type: keyword

required: False

The fullname of dockerhub repository


[float]
=== dockerhub_repository_owner

type: keyword

required: False

The owner of the repository on dockerhub


[float]
=== dockerhub_repository_name

type: keyword

required: False

The name of the repository on dockerhub


[float]
=== dockerhub_repostiory_pull_count

type: long

required: False

The count of pull in dockerhub


[float]
=== dockerhub_repostiory_star_count

type: long

required: False

The count of stars in dockerhub


